# Generated by Django 4.0.2 on 2022-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0003_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='options',
            field=models.ManyToManyField(to='motorpool.Option'),
        ),
    ]
