# Generated by Django 4.0.2 on 2022-03-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0006_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='vehiclepassport',
            options={'verbose_name_plural': 'Паспорта машин'},
        ),
        migrations.AlterField(
            model_name='auto',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
